apiVersion: v1
kind: Service
metadata:
  name: test1-svc
  namespace: onboarding
spec:
  type: ClusterIP
  selector:
    app: test1-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
