apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-api-server-ingress
  namespace: admin-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/router.middlewares: admin-api-cors@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - stage.codedang.com
      secretName: admin-api-server-tls
  rules:
    - host: stage.codedang.com
      http:
        paths:
          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: admin-api-server
                port:
                  number: 3000
          - path: /admin-api
            pathType: Prefix
            backend:
              service:
                name: admin-api-server
                port:
                  number: 3000
