apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: admin-api

resources:
  - ../../base
  - cors-middleware.yaml
  - secrets/database-credentials.yaml
  - secrets/aws-credentials.yaml
  - secrets/security-keys.yaml

patches:
  - path: configmap.yaml
    target:
      kind: ConfigMap
      name: admin-api-env
  - path: ingress.yaml
    target:
      kind: Ingress
      name: admin-api-server-ingress
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: admin-api
