apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-react
  namespace: onboarding-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-react
  template:
    metadata:
      labels:
        app: example-react
        environment: stage
    spec:
      containers:
        - name: react-app
          image: okteto/example-react:latest
          ports:
            - containerPort: 80
