apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-api
  namespace: client-api
spec:
  replicas: 3 # increased from 2 to 3 for 25-2 final exam
  selector:
    matchLabels:
      app: client-api
  template:
    metadata:
      labels:
        app: client-api
    spec:
      containers:
        - name: client-api
          image: ghcr.io/skkuding/codedang-client-api
          resources:
            limits:
              cpu: 2 # increased from 1 to 2 for 25-2 final exam
              memory: 1.5Gi
            requests:
              cpu: 0.2
              memory: 200Mi
          envFrom:
            - configMapRef:
                name: client-api-env
            - secretRef:
                name: aws-credentials
            - secretRef:
                name: database-credentials
            - secretRef:
                name: oauth-credentials
            - secretRef:
                name: security-keys
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: password
