apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-api
  namespace: client-api
spec:
  replicas: 5 # increased from 2 to 5 for 25-2 final exam
  selector:
    matchLabels:
      app: client-api
  template:
    metadata:
      labels:
        app: client-api
    spec:
      containers:
        - name: client-api
          image: ghcr.io/skkuding/codedang-client-api
          resources:
            limits:
              cpu: 3 # increased from 1 to 3 to acquire more db connections(https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/databases-connections/connection-pool#postgresql-using-the-pg-driver-adapter)
              memory: 1.5Gi
            requests:
              cpu: 0.2
              memory: 200Mi
          envFrom:
            - configMapRef:
                name: client-api-env
            - secretRef:
                name: aws-credentials
            - secretRef:
                name: database-credentials
            - secretRef:
                name: oauth-credentials
            - secretRef:
                name: security-keys
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
