---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-user
  namespace: monitoring-grafana
spec:
  encryptedData:
    ADMIN_PASSWORD: AgCpbGqBMpdCEyKcJqm3DQjpjCm8wkdDWhNYcy18KnUj4aIXfPXv6ijhsCmEaFWUkbyLbICQCyL8bajTW7pq6BtfK8tzme7u6euGDy933uYhBeZ3uWZneIfRNodUfcPrOFwrgvwXDC7I22uQgEqbKT67QlD6MzqEhT4+wp9wdb8ACePGdKFFWNcPCpSv+4YQOOSIn9m/x2FxCdMuzetnCofOJUyIBMWDGWAx88oGhgFy8PwGheYWKtdEKh2grD20Qzm52AG/UrHb7cBfjjHHi5afar1IF8sFDv9yk9/heqeeVfUMhxhwshG4eQ6tHtLt9YLnnOw0SUN//d8W6yeST/hCtGPBA27/XmDm9hh2G7FxDbePrDwMSwD8i/ySqthWbwdVvRgogiSE2rV2J4YK7OyC/2tJU3kn5wcxI0pAlS5IsZc5f3vk2fttRxbKJdHtsYByGTyGqhS/EkrqPjSqYJ8Oy1MVxzAZ9EMlW+m0yMttGRAET2lwOWXQp2ptRFkL7EaA+SF9UHpiH0MSd8yt3N0EWu7CKWo4PySa0oKxeu8FubknxZVhsEjQ0YCnHLfSF5+8t075Wm/Uebj+5bnm4UhMvOECHrwCk7yOAjNjy4Xoo00yjVOoD1NZEgU1IHKbAUwiU9viMUk6pLIXAByoTTJ28PM6neduP9TrIZRQIlAkF+sV1Bczw+bng2sdYgj/o1UHn006QiFi6hasmpL+jA==
    ADMIN_USER: AgC9ThgECtUndPo78+W9kiTgFWvjVExI+xi96cqAQnmgzUPoDzGp42CU1b4HEeyaRA1TiiQtoxMcPM7pKEmK1Y+3YD4JF889oAwhCQ2LeIO6jOFPZRB1VD8E2FD6Tim1RU3A8XZ9W6yAZ2OiaROLC0behXRlKLL6abHsRrjQbMLZsmWysBJDUUEJ2wYke4LZs1deUuH8jqETdRFlmySvOUbZ+Cl4HPQtvtSc8lc2yGsMOipdWM0zA0HZ4UlpxUeKbCyB3+84mG4T/HS/ynJz0IEgCLpzdoOL0TO0q9YE1Bixr3vHyRkCZPC0Qkg/VX6/FGKuFO4W6y3upB87japlSz3s3Ie7A8PpMc4PDs3Sg5dL0oS2+F52+GO/VJ4cVN8T9dlQR1lBr/cbebqdl4z1/GD77WaEiYYVsxSc3/KfYoYVMeLbFJc68/BmR/TLIsbmA1e2NOkLuGTBSbhlkykHbWfdB1d0TE6KBwxAltqZrqD8UJmlKoHKah/McfhwTzu8+RDVVED55CauM7WLd893irEGjH9FmoTPJjboii+0KmAN0NwUu/SbQdMsfQCgJxjfNNTHjYOZOCQvHWu6MPSjdXx2931EdDaG3PSC0u7YECBZ2CLFsxAZLao45LfmLg7/4pvE5l/p5o4DdWBym+VuryAd5zTj/6+EwWYSRAg9op2qVKzHU8XF7j0VOHPF+AjDcRazzpfCF0xdBw==
  template:
    metadata:
      name: grafana-admin-user
      namespace: monitoring-grafana
    type: Opaque
