---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-aws-cloudwatch
  namespace: monitoring-grafana
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBFy1aJ/WmnT3oqERlJ5iER5LLlt3Af1syCKbxHhFhSX80YYJCIbNOTu2ru4lJ27gQNzBurAku1hMEuiUaVTeleppVPAIEmV9t+XQ4EaP5/kzQXy3IiRyKpMd5qbfkgRe7R0tfXBoCcb/GUZfBbqp3ixjcP+IX3MDqXRrssgcxplpDzA9bfLDCLgZH3ZJtbTc4cSVpst34sF3gR6nTKwGwBYhHtn03H6cHW4gDyDv67lY63FEg2Q35XJqJBXWhqT9MSxFNJj1U86v/4Mt8BTJj9hui5Z8QkN4oSa2KVPH8wkSGUpNGSymlAqrZ4C2/Xy8HGGt/7dK2n5GXuODCxkoSER5m6AQzfqQxbzpJw80Pe2KNRXrDjLU32zqpO3TQyD7UYSj+AM9UpZigbzSjl/nmyMANk7QHCkqt287sck760lSfSY4/4/V3z6tO76yhlNGvom8TMaRqNmPhge38r0re67qFv0Ril5OHiDshgfGLeslNnMFfuUt/q4U1OJP246zHUetdBLu95ZiA0BGd60lz9bgEHImZCdqjA33pqErSmOf/Ks7l9SYRhe+QHsBKQrGlGrl7sFEDmz+yk2oBXHLGDhIadgjDQ94KveOc3ER0wMdiWLnj3zT/QaFPtBF3lQ/+9ggD6giUlxp5MfGuLpdPRQmS3242JZIskIMHGNgUmvYnHkPjR5OnhkPYArAl6z4LOH0DPQ/I2yUIJJwc74dQ3SOSWYA==
    AWS_SECRET_ACCESS_KEY: AgCa6BwkRpycpaYT/vFvwfTfhsyLpyg06lzxL/FZNvZxXjTK5QnoB6htfc0X6BxjIblKKZFUcSBDp2eCaWYpbD3RRAbFS6vx5Wt78qlELQ7PswbaVKyiWVW6hu6Idd2+PKgi9lpiAJe29YNyN5Ka1gzb9+cEbEyUJwb3TJcaOrMmGvLjk4XjNqx2nKbILIYr4tofwR5vxY1N2IYOnp+P2j0o65QR9GFku180rcKxypjTsI98w3BV4Qff07YHqDDeaEo8L1y4Tc2FDDC+/hUtvYMSZJshyHAh7U8ll2dKn2kRG17an3HzWMKxjw74EQpUos5Yoo62kKGQsLEQwjWeX+++7iJp76yaxfL9eetambfJ42TzENLYmdmZRM2yY1VvEGTNSmtgraVtlUY+3h7BwTgt+Pc/VY+YsRyXEDglwD0/nCc5WAn54RDXLFibgsL6W9VxUymkIxxwgWZtVmijohM1usAKp+riSbMrT8A1wsScfMvlGaUjKoApt/E8uIH9y1AnXjcoOf9e9cYRwu248dTW9koirSH0DLgjae7Wib2Mdaz41wJR7EvANjR4urfw+/yTX63BaVwKA31v2ACt64kfp0RWe73HfnIOKysolfPGNUnX8e+zfTj1SgI/S8NWSLgd6olDx+cy2plceZ5kNAvWCN63oHcbKgIkkRp69fHbZU11QGT3duACI3l/1cHh6re8MYNczQMPlw5PVs3EAHeIWhRiIEVuGDWwv5cXSecO/MkfeQTtUis0
  template:
    metadata:
      name: grafana-aws-cloudwatch
      namespace: monitoring-grafana
    type: Opaque
