---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-github-oauth
  namespace: monitoring-grafana
spec:
  encryptedData:
    GF_AUTH_GITHUB_CLIENT_ID: AgC3xGXv/niC0tQSXeCY1HMpjtxwbFZ7Z/aisQTxBCKjUo3WNMTkusfZuMjHTFSuyANF4nrptPpkB/1PBCiFNm0dcO72X0VSyIR7BTYDBp7BKCuqiVUYBXlj08Lbg2RsS66RSbmjrp22IOoKqjDL0j8N1GjfC5+s2JK0P1s3ujndMSS1x19vts6rkIslNlmQhugy6AhIcCS+etJuAWdH/PCXfTl2ZdCtYSznnOLn/c42rjDjVLGkOXJ+qrBCpaRr9fOjIKtuJG+32EPjWpsjO+MYM3gNPNQxbZzSjqje2N54RGpqyz1Oefe+COGlweUbMvlflwItTWFKOmgPYT68EeFxLCaFinwLsi3bmqu5bsxk1ROHZtiAreBiqSkWV0KBFRzPeO6hTZeK63vEpSAKBDIaCfFg+Ho9zhelpFa7z+Jz8iCXFZeZ0WcEc6CvEt/teW3tNDxqbT/EJOd/J6G1UJx5zkpwNEVnwp66kbiETOX8M4XdERLH1Hu+KoOD65mIhnoC5IAbBs4U7wIC46dqYrCP5xj2wfAhNASvZRfncSpu1h0zMDp/xhcqQ6/Sp/nNPCx+59pitSwJzAGA9rpLKAvyFbC3CifoEcrHKTrN6FfRzyktqdjDVMpjHny4gXGjYlm39J6Z09LyrMuqOs21FL58mL4tvfBAY/SdeqcKge5rC1WEZT4+xQDo860lwafvw2aLD593jgZ/oTf8oiOdyu6ra59Zqw==
    GF_AUTH_GITHUB_CLIENT_SECRET: AgDCPWZJ7N24MSu/b9U0JRTzH2XBX2M13lr+VABvzXLfe8cLC95NZ3wtGUGEBW63iOf/7dQPd2vl2a0+iTQdKmliymOEWhJWJycqxSnWeD85DCbMY+uNEXpTpqf9E9qrwJ3NtkVumr6mFjglTnEWt2V1jIlK1KP7aMs9zdvver72Tl/xOUNhjuQYVvxUM7RWu6myWHIHi9nDhYz2baiHVlUWNREuyFk9ZLlEniJiRGPaBAS/HVxbfpYoTNbdmoYrqURpnH/9cHLlqsRgE/pzSYz0CNYhPPDWQ/lFPWRxOfxnwyHm9CcRJe98jOk/2bdoRSrW9efEpWokmrT4Vks/eFHWpG1tumc3ktcLz/Y0mOe32ylv0Yp+KsRZ/7vyKo53L4wnQ4sPpnVHC575L1u4pCA8oOxlBE4vvi2MaRvwJNRPHvhrFd0mjcyEWrRVmQDe1DJXd/9qGlpPqZPccZ3dTrRzvemp9RPXSsBxAx4U7tAF2Vz2/nVkeO+Yt1MZ+gl726cR8qLWDCFQOlKk6Zi4lUQhZhSfQRpvA15QJkJCkAXI0hqjO8mqlcQz/loSzm9CrfhBMJCQZTcSQ3F4IQra47HKSShnot+VghVAEDp0hODWIj9kijnED3YiBbRyP6oAgbewkAhCmNoZ79cXFuHCAGo0AnDu/14d0bn8ePeDdezjAPlPl9QnKUFk+vaIkDyU2IQYelW/NzxRVto1tGJRopK/KHs29UxW5N2y+cm6iKbLPBI8V3xIgtOg
  template:
    metadata:
      name: grafana-github-oauth
      namespace: monitoring-grafana
    type: Opaque
