apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-api-env
  namespace: admin-api
data:
  NODEMAILER_FROM: 'Codedang <noreply@codedang.com>'
  REDIS_HOST: 'redis.redis.svc.cluster.local'
  REDIS_PORT: '6379'
  TESTCASE_BUCKET_NAME: 'codedang-testcase'
  MEDIA_BUCKET_NAME: 'codedang-media'
  CHECK_RESULT_BUCKET_NAME: 'codedang-plag-checks'
  OTEL_EXPORTER_OTLP_ENDPOINT_URL: 'simplest-collector.monitoring-otel.svc.cluster.local:4317'
  RABBITMQ_API_URL: 'http://rabbitmq.rabbitmq.svc.cluster.local:15672/api'
  RABBITMQ_DEFAULT_VHOST: 'vh'
  RABBITMQ_HOST: 'rabbitmq.rabbitmq.svc.cluster.local'
  RABBITMQ_PORT: '5671'
  RABBITMQ_SSL: 'true'
