apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plag

resources:
  - configmap.yaml
  - deployment.yaml
  - namespace.yaml
  - rabbitmq-credentials.yaml

commonAnnotations:
  managed-by: kustomize
