apiVersion: apps/v1
kind: Deployment
metadata:
  name: sumin-onboarding
  namespace: onboarding
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  replicas: 2
  selector:
    matchLabels:
      app: week2-restaurants
  template:
    metadata:
      labels:
        app: week2-restaurants
        environment: stage
    spec:
      containers:
        - name: week2-restaurants
          image: clover229/week2-restaurants:latest
          ports:
            - containerPort: 3000
