apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: week2-restaurants
  namespace: onboarding
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - week2-restaurants.sumin-onboarding.stage.codedang.com
      secretName: week2-restaurants-tls
  rules:
    - host: week2-restaurants.sumin-onboarding.stage.codedang.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: week2-restaurants
                port:
                  number: 80
