apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: week2-restaurants
  namespace: onboarding
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: week2-restaurants.sumin-onboarding.stage.codedang.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: week2-restaurants
                port:
                  number: 80
