---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: redis
spec:
  encryptedData:
    password: AgC4TEHklsbfspbFTVssWGWkWeAHs5rpsMvTZKbmbpZge1WXsZcXsxD9kgXp1BCxrw/iVEU2cxWvhmmWK/mIqK4asg5DV9wk0WDGwuBTQ8z6pYQZPO8kDEnDCFmdzEK0hijS3r5kPIQYERqYl8Kk7vTAFqNYRrrlmlIg66w+ZgxNI69iFF3igAY7flOZC3LERzl4GrrCITSpVQbVKplyGjKHJyhvVn3NHDGlSSL3I37FPjFDLWW+q4dMhksP2MZDd+sYe0Ra2P8XaeNvWwKCMdnKeinUzYZ+2i+dO12mDwbi3AEkzr4VmH03KmFKNBbE/uG0hLC9TlXETogizIrrYo6BMbZ6rVe2txUVLTNT9reAoYc5Ip9KDAGu1ni9QoiocIOkZuek2AdFM3ZaK+s4vzEK7rTJSXqL6oS3Mzc8xum1w02rzKJvQ6EoGZImADo3FxxW8SYjiLNXnD2rDhjrrfKPHko2F4rAix5l2mqMG91fZITEzZHNyaLiupBal63Qn8kpEuRJTintCOVn+A8jyvk4kZlgL6vqm4byAinj6vXTs9rTmBlkPY2kgwxDE09XWWt8KuiaQK+Usg4vma0a18SImO5diKL7b4Rx7e6EXQ/oi1+yR7VJfV8fk89KTLCB8O6c5JUeS+Ant9uuBaluRczlqb6cJPzSH42VO3LVGJZNvwzqzCBk6sHsBrGsxYfE4DWrpulgMWlFTLGInux6/A21pgAXmsPdv1U07fpP7k9u0Vy1ttw=
  template:
    metadata:
      name: redis-credentials
      namespace: redis
    type: Opaque
