---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tenant-config
  namespace: monitoring-minio
spec:
  encryptedData:
    config.env: AgBaatLnrguSZuZDWQvFwG9xRN9pctjStTsq/5Oxt5Ppgb0Iwl5W5lZ6pcM3N3ktaaqcYdxlrSkm/u5u9r45YcZfzWxi4XeOeA2ZuqP2EjQeYW30IXqLjvRmzpwtAO5873rLx8wVcZd5+wRsiCuN5K1hIIJzQHGBTRNhQiTwK0/NY0qheW5g3x2JIwcjdXBdsrfIPKXrUVOhHJCCuyTiC1YlT05c/02nX47OOCXqG53UJXuR40wScnMaZGFJgGINHDeWYqmgq+d9dljmCeGK37cDRVxXB+DmcRPQlj8A8z4Ec31lS195Cpqs1cSDzsi0CjyGLfNwF9KWhIydIhvb24DmklCxpJO5mBXWNPvD1h3fWA9K8HAY0Tyi4Sl0NRhoPBTOZwMZbHLVkS+V0A4+QYxe+frtdnrsixVhisnRg1MyiB8ZAd0FBwaLaTFG+0LC8tbnvfoUBR9TgAe5e0aQj2led6WGypF6YHmJRIw6Br9WdgcCpdGIoH6iAxx0h2QAhUoKmRLyi2RF2X3zvg70iDh5FhXMKEG4nBtQI3KX9zdgJ89XQ6vn7my2w8aSdIlTH617pwXoMtfAQFlVBXru+p2Az0vJ7z8NUIzYujrU2ijNlUqhJPQO1SIgixHAQq6/G5YMyjCvuexMaYe4gcRaAcH0V04NkeuJV5KVlJ1B458wdq1danDgWCUB8FKhm1FTkgWtLKAvcPGN8XlOPg5izD7DPVrLsnuulsGwgtc3PSf2LNgRImEodvXrCyWfvZ2NwB+a5KaauxGuPZwkEw/bHC9wYZigvRlMD3ztUy6zC7PXQIhPcv+S4F5bAErSunqPti71JlxuT2efS/8D+3qA3fv49JmnjxDuXh3IS5XN8JAbh+Gw/OsctPy86SVv3nVZMVNsA7U=
  template:
    metadata:
      name: tenant-config
      namespace: monitoring-minio
