apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-credentials
  namespace: sealed-secrets-backup
spec:
  # IAM User: sealed-secrets-backup
  # reference `infra/aws/sealed-secrets-backup/iam.tf`
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBexzdez3PaudtrXLVP74rHjD75AX3e/3MKReRxdpiRgpTgi49vsPmHvAsexbackD6b2iSiQX7ug+judOp5f8fwIPLspyJpo6o7x600rjJshAzvropNV0azX7n6Nanb3CV043kBVRIaQOWuWVjTfCKvjyY6me2cTDL/QhncRLNUWa21AZVyqI1k4SmouMnV9GiEOiZChtpKrWbn1OJEmJE1mLkBXDKo75OLUXM4fcN+jfvEu/dehrjQTbK9u7twO7y2q+fSjz6fFPk+EobZ/z95vsyRBKu+pjjcAILftP1kD0euuUcQYjP06Kt/B8Pf5ddDMefCtpATtIrsBqTHWs92CPPsMQvrL45phPYKEeZyqHa3MWttDgOCtgtg0tvX8E9pH4DGqXQDei/uiWm38CmFJou28ZzDBP2cvHckY0zjZ/isFcOuc6mtyacZLxC13uUZ3x7kBl9CKI+F2ZrQ37Rst3dAGGEhJHNSsPMgsnkKhc30w6YDbqRlnvZLpszwLhX+PhDwdej7B17oqPGHPMOO5de/RzPQlK4IfBO9x/OghcXMexKSMB+1hW4osTT9jHnYBhpXdo30gVwh9noNoqTKCaGUkZCwXNypZnH2xedIQfZQbmbRHHA4phq37TBQdOAppZZl18iNEumAc/XTlUoVtwmKDYNmSGGckjuhFMtmaH3g7Z2po10RXkZbGISHBDiHIrRHQ9XXlGmS1c3L++Z1uMU47A==
    AWS_SECRET_ACCESS_KEY: AgBvJ5PPOEihXXalG5p1OdXXM2Xj/sDbNqsITJ9cxCLZJxZjfiry1O89KkwQDnqBtHEH2GB49EGYwDdmPd8U5YEcmX9VdTP9GrcpYDuQcj9gdIdS0E3gAwgwVDesY6W7REMrzSjVRD7yaMmfxTz0aJRE1oJiSirrODATfN47Bx4LhgSIU58XPK/6dpc09QUeUvUlch/rtG1GIGWRp0W8H0cZb+bSyQYI5vr3aqo29X9GUZAJnpt5Ydvbpa+FGD4Y/UL8p5jAZJzLH3tVfcuiMFi2owY6M+lc0Vf4nFEdyRmPTsmfpYXRoCHAbLDpYkFMzuGsMbM0ybP5oCXKL0ObxVr9omzuZorTgMFGIhvtQll0/E1aUKaIIDpQ88XskobqmtFXIRL0fi2D3tmtnoZSEy/EpfF8CYNdQ4DVC8EjtXT3tJFUtn6PxRPchD4tDMEQBalea5Dm3aNL9XAVCNAcPDiyKMq5WQGZxBnMEaNFgqrIiZv02xhekx+KdKjKpcXwbEX3PRtA79OK4GG5FZJd5kveTWPtXcUbCmwzcwAOPa3urQBWHoj+r1DyFjUly746hzdBbXwhv/6UwqpTyQeYB/DY9uA1fGOfvQtiZQjJGzoM5vrj/1j0aGtgTyKND7Wlw0efx03e1ajUailNoB4FMyVMx8nPQZ6humLI7iVwcilT/9NUAOaxdf1O+A+b2BlHiLMzJs1WSx5ZgTfxD1cNIj0Ri1BN0WNgzrKqO+jrUQM4xdEBJAzeeNXP
  template:
    metadata:
      name: aws-credentials
      namespace: sealed-secrets-backup
