apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - aws-credentials.yaml
patches:
  - target:
      kind: CronJob
      name: sealed-secrets-backup
    patch: |
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/env/0/value
        value: Codedang-Sealed-Secrets-Stage
