---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: plag
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgA0xwJ15go2s4hij8c+xD0MOlUm/Lgn9uroL/n1nLCVdSHqwLy8fnf/N45uTxLdbUPtl+ds2RBjXJKhsUH1cShNI26wuUtJO5Elk3PC+vljTFq0h3LvraL/25g/aNu1HZ8WBToku47DiQNtF+bBzT9eaw/kcRRucqfpO1Dqxpsdsw3S1IBdBj/i0mYUsl3oEtMfLQc4TC5yKgsi83PijxrTyfZSBl1mP9Q0h38RNMZXWqsg3vv2Q5C/5w6YXN2e9ip/TitFmj/dhB0W39uL2QX+vrX60uXamWoPRo1W1yri/nPJE5yIZblIbPoNUu71B8Vu7pHclSdC4kfF5a9FSkckr6SEcSSDsKy89I7wFgeXg0SAItFAIU1w6i4f5d3AcelFDRmOkbHtrHyItm3RAQbP4GASMOHHoLwIaMYQq5sELu/n20KTgCN9nHPJeZgh9zBqxliUx1txY1AJAFhNpQYc1p/baEQpAY/ML5Gub2obtdXQvFUqwNdQTS0FmrpOuNOUhgbbUj3yLg19RSm/+I8t1DvayTxO+N3VjkHVb8ieUYwL03zgc82q53t1UDETDIHL64vYATyBqFAFPrviK2r91+DvYtLnS4wwW3PjGMLJpCGBDS/ucZEIJgLwKLMtBTce2Ju3PF1FOJ3lDECwjrhuO9QVjH7i9clI4Lz+gA0ejVfmaeiBYnhqHdZYRp6cbjAMG3MwJTo9Nhybq0MfBBU0LtJCjQ==
    AWS_SECRET_ACCESS_KEY: AgDSHrqOjCxTjLizPzMiJS7+4MwPuLitkDDkPBt0HfDFX9+SfTT9b5S7n84540AebnHF8AfNJpnhzZA6OH1cMf0VWpMKqfltTjOmnxuuu9LQK0JHhPq/l9l0Si0AXjrfDfk0BiBLjzK2C8oEiDbLYwzfebnyXheJnB5WZT8pu6KZwyP5AtILjsfz3Y3/qH+u3gQSQmavjdJyHBZ88o0+U3/SsdtKEbl44Wn/JMlmEaXOrNIlz1Rs4ZRNjBxxErwoVbAIWJ/msxJK1+NL7Z79JRorpAPRg4aK12ezuSODpWeZL+OOvsWfq3Q4trbdjnulQ/Bk0QVdS3VFm8ep8mSjc+9DI8p8frBt7fRfE9grO9vBagJJHaJOi7drs9B32qoHRFgyHDANzbj+DTWAvqKwuRsuv4arT08keY0CS80ytHlJ+/vmp+XJVLuAsARcH3sBqqgyRbwWEyRwIT8wjgkFNMxkVj/Iaq3Y8EaLpbw57D1mNaVe8Q7yxoIbt3b/o2mItY39AZ7btx9dM4/MqDVZWV62cXEyM26g2NyZnWGJK0aDvmXLn6N5nnLcJv/FZH3JEOW6mtybKvXAACh2ki75zomPMZniY48sedV8hsG4i21R5K9LNrPNPIZ7/00szoLBkZXJGI2cYOg54vzkPut3m0qztNWkz9t/L+JBw5vmrRzaAnsYd3rDVk2Flqdywt15DVW2xgVo0pkPteq5ChzwAJb6IxX9O0w4K0w/Fkjz6BU3GfFnRwc/JPco
  template:
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: plag
    type: Opaque
