---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: plag
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAU7GvYnYuH/3lH7bTjLs3QJir/3o147RXAS3eF+ip8UfYIxCG/fAjQA7jb2noTG/rkQFWQiVKVAkb7xQz/CzwhJVTmRWcdDoGn2I8NQ+dNg5pZZTbFLJmW7XzB9/x98k0gwZs4/XUl/2HFRfs9SQYT/djtsG0Ga6lqENNFLZaojRPoIapU7VA1dNJHzRnQ+GhMFUBtNV9qyiFhJpQh8TfoOCPFpxIDlQUEPZbJbGLmrsI7xe7Mjc2JaZdniEeJ50/66+qMfZlV0v6RnTMXJyouR6QWMuQVf5Dijz5Z1XliiMgBr9uE0lTfyyEL89n3663o1t1b1Xi554n2paSDtX3wjET8qssih70TkwwbUghbaB3fkGV74FP3NanyQ68oaEsDdKyaQs2dKH8qU1gnREgAFC65YEK44gsG4U9jF84dmKBjRNb6feqZxHD3aIEXkGW/K8RIJISPc/a9ATBPqwPR7eYERCKeWlmvVD5FYZPp4T9cJ5jn4mhejqBJw4dOrmAsWeY/ZRDf2t7QHSMJaR+q5VPjGFk9BgbOwNaGU+AN5yTUnqqgix2r5WDTm3QIt3I6bEllfY8JoxE5eyXwX7WP8jruB9ywwm1HX6rAyPGJRnya8DnYHhbpWzJ7k4F4JcNYcGq+iaPEDZxFrKCfMX35Q6G83mUBI+mWEdbhKltwI6NH88i2aP7C47yIIvc4DdF2miCj
    AWS_SECRET_ACCESS_KEY: AgB6U3ZAls+D6MUTuhILlnZSN+EiaR3MRwRBoBZnHeMxpuOLG2sOw/ToIXQOQQ4jtn1sPZpgPxfkuCyUCdNNrXGlo5cGkVuAWJQYXLJ7E1Dxu6f0Gy6T9E5nO4V1aa/lVzQzkCfOMBPOLImezjQ8ikjW2cMKCe2RhlFYd2PqCCTGpefN/L7hggn6+2DkHV2eN0gtTd5mzRflQY1eYZIszCTjwvyBN/oFqbnCZ449+VQmb3Jh1BgFdUBxVcXavOIp2sSdhmMqdwzL3C4AHgdWc4VW4AvNEn5JXz1xxQSSVpRCSqluddQITmx5cW20pyfFqpl7XAQnPaUoNFupnLbc4sRGX/pGBeW+UOt2TUoBa+w++Z8qm2ccD1M3sdUSCizC05PTbJ36mtW9r+Lntj8y1iEgm7X0aVGeA/tmdI/iAbmd/i8BqhVyO/Q8qfpV+lD4sHa3eWNazXUUiLG3xivDI/gWkvDcaDPd1Z+yuNGRSXvcDzo74YrcCzKmXhGdTbeqQozVl1lf/9znt0d1R2sojHfCQQp74Qx7eZk2FsDcVEVgLICNa9aQ9m4iICjqEpWkR5mgb7wibWl3Bs94tzDoranwheq2CL1u0Vyt4/nrTT9mSZWD2sK8oDUfrNoOqdr4WfND1zsGwfV5akOqPc3gQAtw352CZnYdg7A5z/M+q8NwVB2WHIBUpA7l/zfSBBQNKe6QmRlb8YLzLQsVno9D
  template:
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: plag
    type: Opaque
