apiVersion: v1
kind: Service
metadata:
  name: runner-scheduler-redis
  namespace: runner
spec:
  type: ClusterIP
  selector:
    app: runner-scheduler-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
