---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-api-user
  namespace: minio
spec:
  encryptedData:
    CONSOLE_ACCESS_KEY: AgAW3SfpWt+cXQ3V4hGSXm35ZRgAsDWKjaIDszBdHI7+99Ttpz6QD8EHAmc2MXMZYHXPYV7ZlEUna3SehAjISroXRx1VveyoGvDpQdKAD5BUx1h13oU6gq9K1J5QEaCG6yU7NfAG5ScQyhoh3Uw5HpgAZMjpfq/E5xzgXmoAyfmSyeSQ0JoJ/692eFmEXJa1Fmc29IZPsOucHKeU1X0EgUVhpk2bYJi7F3r/iUczzVn8xefUYCKfjH72WdbXOFZPRrn1xpthj+qNQir+NTERyMFxOSBmmizQ2pGsBxzQB1ytyt0WCdD2CNiiPbtRg9VHYgzHQrnwVWKq1AZrR1a+hAqofMC5E15jJNtcHMNDFxnWttw4lPCw5Me3JE8DI1P3P50h8qmVI0M2Hd25T9pSaMWevTYP43Pon4iRUNvz3oIHeD7mgsEIYJzGb4OLpcjcTjuk+yefianPlJSF0bU3zwOeInLygIr/jsaXTQcH7ad10HR/YslSM5QX/Wn/6zodfN9kyqRio0T/vV6/pqdfUOa76cFcZzGI6DpbU8bUCvG6AKNpEPYYeHgJYYhmXTS6hM9/E/uEw5tnuHUpl15vJgSWSfn83u7mgjEpEFf4Ir3zXUUaQPdmR3v3rO9HLP+0ALBd2mjIm6tqFxWWRQZKMQ53O54mjRmHf7Dp5wN7f+/+FfwaKkagarwWWbMVoGzk6wajNov8EmF/RPI=
    CONSOLE_SECRET_KEY: AgDFKQyMYbjQDb0GCds1Y8bY/iSVm97IJsfWDOjAHf79Rr8s0xSCjPbUliLeyjDuVv8N0e+YEIT37qleeHQ4DO5n5ctfv7kUADhyipW2uVIOGn49IE8e3OaWUon0PhU127e1Lyi9yQoor6umaTAvSSs79U4va++/09Rd7ecMEWAiMrTyjCtv3dQXKXQGjTAH0Uc+Q5wUtIm5ieaZgXRXaLUmO5MyE2oueM56Z/k0mv0x46S1mDZaUT6Sr9GHBMF2vC18B6Tg7nMWtrKdXg9yenLl/stLDFrcn+BL9xrtyYECgONbZFjUqqI1tfmhTW4PUxnEW3witOwUs0m9v80nMzPWZsJyzmVEUU0gB3RKSb2mcp512Vk8mZZ1K6aKZkXvAu1vyjyhO7ilmYxz+p6Keo80mgiVzRetdqmWMGzjmqNWmoehiIFwgdi1ulP2BdtYV4YaN82OScrEqpUoYGh1Dl4AMvWjE3zl6tW/msEUxQdByWvS//iQlFKyPso+rcswEl/WsnCIk5MhOlIbAiErzmznfKCBD9UqCQHP+bK9RJcRxRwJ094WSEQgoyH/oY/XRt2r73Rop9IFL//3/TNWZdw1PiCJjTWAcZw69HF0J6Zf/f6ps9cu8AhfQFPZ4bB0Cw1P7MUXlS7WjN1WyP7/z9ypFaqQo1iG+SlaTx9PBVVuZNZMaXmwWBevbPmilD/h5cDs/gfzLO/xjqXCdntlwWMVmdsn2A==
  template:
    metadata:
      creationTimestamp: null
      name: admin-api-user
      namespace: minio
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
    type: Opaque
