---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: iris-user
  namespace: minio
spec:
  encryptedData:
    CONSOLE_ACCESS_KEY: AgCN9cIfIT5GNLKzEhspdp4RDniHQRcuvbdx7EDwDHVVJDpL+TVdoHvpTxI9VPu+EcXrTVgqX8HBDxobg0LzXU7q4ZkdaRYNjbhXQFmXa/xkF5Thbr4qeJwSKmU9nWiCbgxQFPvKNHtioE5Kw5pz1jCEE7E5Exa+734DUpNGzR4/bbIf80gbBF0UBCRd1A+YDRXPEcc10XWqkyI6Ebp+SLjOtukeHMUn6JctiKnYhtPnXHSYx3t2Vg/t9FxFzllyJ9MwA6EPiyGhcNGxvokn27COwmhqRhM/ku3XMjQT/wRyHJfeUjryl5ckJ1OBtGFXQaZif8qKZMVuBE2IH4Wi6WjcH/FHb3hG8zpYvyExzRC/BD9saEbvx6wltj+c/+R1hCTkyQ5JKb2EK95VLiOuWLnLbyLsI36MaO3bcDeVna7wl9YvVszWux+9c4lrTmNAmelmoqmxBDxjUuHG4W9MidCtgLuhsKYz7hRBB/FGFv0l/skoLjaduZLnLbwNUMElRX6u/txxLlXNzKBC+/rqMrzr2+jfa5q6y24vz4AmRTx9Jf1THng3nUMN6lHM/qHamyrTtO9S0Ucmq0sjJLy38m8WatCzdsoAdDXP6+oQeMhzGynydWdNvwKraahtmXArw7ehjYxjUIuVwbrSgksizTYCzPa+GsHhFbx+VySJaS9jRYdN6w/keHkcFEUavwKxyU41Wqgz
    CONSOLE_SECRET_KEY: AgBRjAdRZOzVDulApPM94bFSlzkr8Lzxx8GD/TP51DdJ+h0vl6SJfwwGLDViqEBferzEvmkbRH0NxvY+UuUm9SoRuBgXRJY9kNvANrXam/af5klJttCtaULSIIMpH/hiyzGsFfFqixTB5U+QXVYLjaXRqLh3qL8NjlAliVB2WyV8jDXbdHU7NrGRVcUY51nLgMtDLD7IB4fdav0ObeGH92Ecnoa1/RfsqHHkD+6l2TPEO1mX5NcuRJ5h5Wi/qlNyutX1TCeAZoL+6RlRvKBulzyapnkQYZzjMB7yu9X9aytXjCAt0G0vMU6dhjAqi8e4xD3qnG++OBWYAwnBg5DzWmihmP0c5cTxWwgRqdCU4NifcIqszH95GHqMEcQWUthYiSONL2V5RctWhN1RpYMHUdQAZa7kHGPkwChZ5FJPBoESskmygM+Lde6tDM6Q1Nwdz3GtSnuFyea+iQ0rps6FVxQ28klLZowwx7WkJ4vjHISlDOZrXgvFGCyz3YKQEp0yyDcIW65B8t448Gb1U5mz8EcXyp9OHOH1wUPgGse6HX0qDg4aeOVJJHIqJjQN6Yxn6OYjWWq3cgss+SLe2LVh2JPDy21ITDsIqKUK5x+xBXQKO76PRcrFgZnlY1VpHXHmwA2vEoKnhRz7UqC9djVJMGdxpV3+5rYiw0rDMewUUowyTWFZVqETsqsCgCDQKjNVSZwuBsSP6sQUPNPRjrI6fPPzZlQzuA==
  template:
    metadata:
      creationTimestamp: null
      name: iris-user
      namespace: minio
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
    type: Opaque
