---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plag-user
  namespace: plag
spec:
  encryptedData:
    CONSOLE_ACCESS_KEY: AgCgoJd6klbhTQf+ICt9TZIeRYvEhqE7of4UhESpJ6DRGHLsHZkSmCRRpgdpQtxS3r07Kb/wSpIA26vbM9o8CBShNHMEsZFfuO1CugM8X3BiQwAve2/7jNqFLTC7lmd+VJKX0+hCConTxIS67EhTYhuCYN/C1xQ7aBWRX0zsx9wkXWOcO2Mw/B5eAYCg31mNxFUBYKabY4BRtamg6j2o7hUQoGWvQWphzmy74KweNg/cULT0UdIYLWQzdfOT/T2hIHClrRs7j6lcVXE45/d3SeekYHz33KVFC7TbZrh3Plcy7kxb04gsqoplNiN8Yi6RMfpvBOJGmm/3S6DKXmbKgAFOZvTzSUEYaLRBaBy3mNcecWmLpusMe6SyS+wqwzdb2P5Nv5qs69obj0e8J1te1o5QlNQ495Z9Ac8hG1+9w2156/Me1LbhRum7PiVsIsq+HVtNQRxZEtQAy2Ldlb0U6WnIjtmHuW67I0R9Hh8g7K+1bovcY8pDguSTBNOw+htY03iCLJggs1QDVmXmcNrqiw2yjBe1VI4UWnLakuPNRQ8uJG59+6YYfI6UracCekc9o2nC84p5BcDxiUK3EiIlaB1xs2sAjqwh2Zi2dkT1CyI+J3168cVGKD4bdlasVpIKFW0qMsSI5g2MTNI4AZc3DFHa5kaKt4nSR6QedMNlW0dEoUxQsv7ooTvfzO2EcSegvJ6s6EDg
    CONSOLE_SECRET_KEY: AgA75PiszIBUsOAYS+9m1dhQX7Twvppn9Mvltg86TsfUUgrPJyUj5rDHs9Hoi87nhRNGg3TAFxzDRzzrJfzL/ItuRPBWw34WVK2LeT52AOITNwuhxCcAvo8OwWO0ycpXzu3E4nW/fnj904pd9JmrK8YO+F3LByW/VEf7weu2MEy1CqQXzRw+P3KuaxxZPVRm7VYugeAPMd57Mg61/xGieTz1Erk2Va1atXcSOU+ziBA2NRRb9tXaIb1nredKLvkaL3UT8KVBuB1I3PkD8hGuhZX7F1xw9UGbx9VcyhtUlSRJVzR+43MlKEt1VOJYg4h0WYoPGJwcaRV63rPEDjvIohtleB8czxKSlWqZWhs8tHIt5SmxIowRxepntAZhpLoEGVQDdCELI01o5+1svsZxHARHdNe1Kc4UV5g8EC/DcnmVBjum5IQKdfpm0Op7XGHikLT9EJHs/DZSmNhq8EPNd1xGsBgTqoHn/YPoqhVoh1K9ciUk9RT2cr5MwiYhnb/jpOnnhw352AzG9aWX1dEvQBkn6OZz3H1UxOoV/EbeKAgqJrdC1jXQ3Av/zjA1qdLIqB0AI7nHBZ0ZtOZdcGfubym9PcXyf27j+P2D9NXHFjd4mciEQOqWN5G2csKLWFCIsftpGyd4c05zVlHnQsHQab3OJq7bgIiw6p4PnCJHxG6mvITrOApEHuIN4zC/XyU1kDMzMzKcgSEPDNHDC9A4
  template:
    metadata:
      creationTimestamp: null
      name: plag-user
      namespace: plag
    type: Opaque
