---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plag-user
  namespace: minio
spec:
  encryptedData:
    CONSOLE_ACCESS_KEY: AgCssLbzHfzcbYxQxSI5QF145Uf2O1CN2R0mI1vh3eXNlrfEHpuJ5dJz/GtLpqQiwYiLPboFbqbgWG6d8MAhoJwH1XT7qQ0/Dt6LGwPrfxEyukB1/+VuInGg6Ga/penv0yPfGNr2iecpVfhyxdXd2hVevVwApcxpKyiolKB2tRUaR2Wamj7GLFTB8qVUDmZUHABHV4RtkVJ0LaS1uEkwoWwtK8TQZCFo/8xtVu0csFWZdndG+OXBn1DPMBrTWKarIndcFVh6s3aJKE4+zdb8LpxJuttds8RL8f5JguECfC8xrPWmY3jxR+NEAdgiY9P5yn9o8xpg3xrsd60kaM5TL7xok4WbVMpWHvHFJDjkIhX5wx1vuOqasSZ5W1fH6Q+Bik+NuZWJvXPOxNzgDkmM1QKjanqGwQkh520DBm3V2jTaEiA5kngrBZTIvIaMsKbG3NxL9MGjSRY60TyqbFEN09LJDTXmqbgmthr6fyYd263hjRaYz2Ig//fjGnfMuwuSmCMVAltiOyFklZO7+wFNgI2WKlrkL0ratCzzPs+HksRLrf9aioB6i/svBbyHJZgdgrejbWAgaZySaXl/7cfgW5DadKODU2e6CNxlXelYq0KQFjh0nFB9d2tzfquOWbUEq03mlUKraZaOFhBddoZ/toYW2xNQbBlI5GzSls4dGxZ7Wiy9iY3qjMBScmrsRs8TcjTbJ3lK
    CONSOLE_SECRET_KEY: AgBG3t3oF5xAXXwsaTmy6TBg8iuhheLsU/67Qj+unB3ntuCQxQsjo2BiyBt7oQpoHdfhaWbZo+uMx1PXTWEkBjiHR3jHh/NAdTsKjT1Tz/Hk0XBwnnpqUTq0I9X/0ihMcMJS9u03YtdMRXrmn63yPbU8uJvyIU3ttbUjuSQW0HmJ47zivyTpHYQaamsJn02uh2GUV0Qc3ZUdJ5VtSZq6IMLwu6Pyln0YkMaPzR2YD2dUjzHhilrlnlMhD33TN85YOlOx3kd3eQAKo72UY8yEPL+FaazKiB0RcrPVmwUg9lhQcIRwZyUbxXva6NQknuKs3oFcWgI70CE9C73nNVocCyu3cZm8DKuixYDpR3YrKM8lkNuCYFFLF6qz0ICxab9/zcsS6OCs09PuELT9ACJ9PUzJEiVpv6jYVjlOBL5P5rrHyTOnoEfYSL/exevuOwbitrsc1Onq+h2oEVzc5EFFVZZhAM1vBrYZW4/IbiNPmCTJ+Uq6A6rhtH/H6Chtph8h3mxwKypyn1CI0tOUc+oD0LVEi1Zmvleep9/EsHq10OW/4G8L2A27odsm0eGb1FTLle+vcq/YUzo0YKzPqBSydJVHC8A7TCkK5zgwv9E2VAp1/ZBvGqj2Wg6T50hcOvFI9TQDZ9unH0vd1tpYCaXpG19u0hnBtXehg/ztt6x7AgMttGy4ehRsf2h8CWnC3uElOxNZ6e2RUaCUYJ6g6L8C
  template:
    metadata:
      creationTimestamp: null
      name: plag-user
      namespace: minio
    type: Opaque
