apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secret-store
  namespace: iris-legacy
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials
            key: AWS_ACCESS_KEY_ID
          secretAccessKeySecretRef:
            name: aws-credentials
            key: AWS_SECRET_ACCESS_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: iris-secrets
  namespace: iris-legacy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: iris-secrets
    creationPolicy: Owner
  data:
    - secretKey: RABBITMQ_HOST
      remoteRef:
        key: Codedang-JudgeQueue-Secret
        property: host
    - secretKey: RABBITMQ_PORT
      remoteRef:
        key: Codedang-JudgeQueue-Secret
        property: port
    - secretKey: RABBITMQ_DEFAULT_USER
      remoteRef:
        key: Codedang-JudgeQueue-Secret
        property: username
    - secretKey: RABBITMQ_DEFAULT_PASS
      remoteRef:
        key: Codedang-JudgeQueue-Secret
        property: password
    - secretKey: RABBITMQ_DEFAULT_VHOST
      remoteRef:
        key: Codedang-JudgeQueue-Secret
        property: vhost
    - secretKey: DATABASE_URL
      remoteRef:
        key: Codedang-Database-Secret
        property: url
