apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: check-result-queue
  namespace: rabbitmq
spec:
  name: plag.q.check.result
  vhost: vh
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rabbitmq
