apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-console-ingress
  namespace: rabbitmq
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - rabbitmq.codedang.com
      secretName: rabbitmq-tls
  rules:
    - host: rabbitmq.codedang.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rabbitmq
                port:
                  number: 15672 # RabbitMQ management console
