apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rabbitmq

resources:
  - admin-credentials.yaml
  - admin-user.yaml
  - ingress.yaml
  - namespace.yaml
  - rabbitmq-cluster.yaml
  - tls-certificate.yaml
  - vhost.yaml
  - topology-judging.yaml
  - topology-plagiarism.yaml

commonAnnotations:
  managed-by: kustomize
