apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rabbitmq

resources:
  - admin-credentials.yaml
  - admin-user.yaml
  - exchange.yaml
  - ingress.yaml
  - namespace.yaml
  - rabbitmq-cluster.yaml
  - result-queue.yaml
  - submission-queue.yaml
  - check-request-queue.yaml
  - check-result-queue.yaml
  - vhost.yaml

commonAnnotations:
  managed-by: kustomize
