apiVersion: v1
kind: ConfigMap
metadata:
  name: iris-env
  namespace: iris
data:
  APP_ENV: 'stage' # Running in 'stage' temporarily because of errors from entrypoint.sh
  TESTCASE_BUCKET_NAME: 'codedang-testcase'
  RABBITMQ_SSL: 'false'
  RABBITMQ_HOST: 'rabbitmq.rabbitmq.svc.cluster.local'
  RABBITMQ_PORT: '5672'
  RABBITMQ_DEFAULT_VHOST: 'vh'
  OTEL_EXPORTER_OTLP_ENDPOINT_URL: 'simplest-collector.monitoring-otel.svc.cluster.local:4317'
  JUDGE_SUBMISSION_CONSUMER_CONNECTION_NAME: 'iris-consumer'
  JUDGE_SUBMISSION_QUEUE_NAME: 'client.q.judge.submission'
  JUDGE_SUBMISSION_TAG: 'consumer-tag'
  JUDGE_SUBMISSION_PRODUCER_CONNECTION_NAME: 'iris-producer'
  JUDGE_EXCHANGE_NAME: 'iris.e.direct.judge'
  JUDGE_RESULT_ROUTING_KEY: 'judge.result'
