apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: n8n-workflows
    files:
      - workflows/workflow.json
resources:
  - user-credentials.yaml
  - integration-credentials.yaml
