---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-user
  namespace: n8n
spec:
  encryptedData:
    N8N_BASIC_AUTH_PASSWORD: AgA4/BqHYG0ZOIa6iG/GiKGWWTpgZJu6guOiYPqd5Lp8IA5dKwQQVzOQp/8VY5gJPUm5LJbO0sKshwJ6evJqyXikZX/qwNCdOCRGbexFWLEOj9Z6tWhZ3qCwloAbRxToyZmoGVz2SMp3C+0SuT1Y5LvzStYu6P3FTOIZAR+892okOENibUbc1BlrBG8eRYLO/ABWobcfhSEJbqXKvVJB13+hBtvhqsqnjaYGjygizcKlYRJxDACzFTeZLIgn5q6+a/hp3q7XVYK2uVlsBupncepoDUhioxixGQ2l3Ptv/Az1FVuZ1QdtL4NUn3BxOncECzqQoWZbLf+0GjWhsmO+kRe5/5xwibDsA6BDWifpRyvlHR1jHED6KHRYJLnLoqXwcWPo8erUG1UgI6XmXT7dzKEVhwtemZRedJyznvJ+pAuivUksdHYuex+DKBaaNbAhQ3MUr4BOwVk+GNufA24gXLru6zKHKOrJlKyWj5DEPSvohnr2m5XWgKbBvRy3hCqdU8iqkCw/c5MMSWneqpoAdcO0sKJLt2vjivFfY55yz5d7jO7jXZfJAKYMkkkMZTj10Xa4IFc3vMw0d3oujGFizTdDPMTMqQfXr9xl99NmRwK+JqHQGxYrr+LyRSr8wx9JI4LKHoOVRAfhCOiUWTztKgJJhymIJ4/UnJnkymGp6cI2WM5SqGeT/d0tiCDhvw+KSdshm7EovbvgSCOYMQ==
    N8N_BASIC_AUTH_USER: AgB6+g0+8le4ITyNFAWomgfVy9Wavz5xVrAomQj79kLgg1prieO96lzxztddnBbNGBcgWRR2MwkqC76RUulgxj6IrDHKMvYuBSEAC2H24wqt1p4qF31iZ3ZqzMvq6WgxXD5J/m5wQL20NEyAtkdGDutpcez+V2C2xHDJBrjiboOn4aaeF5nnVwotKdN7GTSf4aIFP8ESc72xsdM1tRPJYG4ssLFTlSiDCT3FtsbgYnD7CkE4w08uMrTao7S2WBBlEZ4uXWndT81ecS9WkaFpX02rOaEWha6K8gHKcwGVaJdG5ePnX43cNoEZlK3wN2ipSi/nHIxQqQItT4hl2/r2GFfL0jU+aJNrgPX+uHosDte1KFp85Jv19gYGbfR785lonkmsA9qi0hKYHbMug7l76cGxIDgueDr+B4eqc4mohpjUk0fwx8W2hvs9Iwl6zM7zyh3CpAVuXN06IiDQLf8gO3rwJH4NrvnFwCZmgP3gYDj4pIUWZsstKchFdOO41Guhnk3MtUhOHUTyd3kZmyiYYNPINgL3QRdOwl0d2ix1bEGSuLBO13KTpps6jw+N/5Gr7yNeYV0BLxbzrDWxhQWiT5N5hrC6FF+d3EU8jP66kHafMwun1I3ZctlIpkJFVJAVZnNQlgudWGFs0dU8OshpLql7X1zCvidIw65m/PL23yNZ+KTrhNydMhbloT7YWlL8Dxp3bi1+lkn3+eUNh/7oXRzRoNQ=
  template:
    metadata:
      name: n8n-user
      namespace: n8n
    type: Opaque
