apiVersion: v1
kind: ResourceQuota
metadata:
  name: runner-quota
  namespace: runner
spec:
  hard:
    pods: '80'
    requests.cpu: '40'
    requests.memory: 40Gi
    limits.cpu: '40'
    limits.memory: 40Gi
