---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: plag
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgArF8Fkp3MlZDpMWZP+TPQf8RH3UCzSYUaMUv1J0kToFTAMkbQ63LDl1h+PHwyKdhQvp9ZCETSpObndh3PMK/F6T8g3arrmYhxn3o/pmecIcpBSDMJBgUn5/hCPMnD47HYdZIZek7Wfu1x+pI6AEqex6QubggtUw1Od/sZaj1JSdGdfXnF4U1InQY20dqeKjTOhwO19N1HroSgIxfh6jzAsn4hJoPrU7gP8X/F/0nggQLKZSbyK7oQltGZcYiAwsfmuMfmSl7jBgNdZb9wbdAPTZtMFNPtGyn8ikyMB8IFYuMYtLNyuBJg6ltLS2N1JwnB1mOu0X3zh32PTBwBu7Yjp62KlttmUbNfAtLGUhVaO3zv+iUFH18OwhNGfQVdjR8zsYZqZMLLmWntEgkAAJtX5IYPeIyM52KsGadTjhpt0x/Z2fnrUiNZqGdq2Af0TvlbmtM88fG/2LF9FLAGH0smWEGSsfmkPZyZIr6ys1Mw3X/WUOAyHrV/+jfvP+gJAX4QuLWZW/JXJWibrNsDeZ2zqdzr+JJMPES3h7+LQ9fJniZMc1gPHhoDL52Jj0U3w7aEXgP7O61hI8N4iLrl13QhRnQ9KJak0sShAzilnIeY963HeN6L8OCFYzOVsv3MOr4LZV0xpsWgD3ndJpRqBtKj5B0p7EZ2Q/y1gsTPm6foj5tkTjKcdWunIRsPojbP1yhuC0OPi+4DIBYzyolihdmv5L/vF4A==
    AWS_SECRET_ACCESS_KEY: AgAaRFT344TH0xlch781omF8aZwfLjJQIx9ijaZeuA2SluQR97NTZMnTokcO5fSoorHGF4Ney1lFOO3G0HnPbehSnjwauBTI+O0d1uSZ/szPO/lW7wH9wELLf/SsKqz0YNuo0MONhUYLRJVxR5T99fyST7QbrKBsl+tQlN117ov8+AJvP6fwi9jWGZYfYEr9k4zkicMfBeRpsJXf9MCet+GqspHOnqPGgT5ERzTOphBAET9Q8AOczrKD2g3a4qxLq1k0vUJHRZCL/Nsah46kxcJeQ02N8BR0Vfgc6tn4kB+qnDPp7iztw4wy9P6LpFl3G5DNy6DTGqjb/fErOFSZR1jnJd2Wkb/P8Jjgft8eXbcAjQJEwz7pf9c+ayy3iV5ZNKlGByCv/MPpjMUwTfilAJVgtVfEPcN6UYQXWeZXGRJijp7K9+UDzv1F6Rs44rCT1bVIpKFpyypEjxvYxg4R6YPZWkNTTwXGP5lK8oXY53ejIjZMSmXle8ne3YiOYmfyd4PGgb1MnloX0pKAHsSyx3NBDuTWeyoMzywekjxEZmicPIm4c35Zc666J5f8SwORvio9P7NYaZ4ZtMzbKLsKyxfLHNSJ7epzBwPY/zPK0ZevS60AC9U1GXlW6F/xh4MTav8Q3o2i8yzBnkqnxcEDJPs0POXUAx+8waojiwzQnD8WRJbYk8+5I0sIZsTNyOj8cvknFA47ljaxYOGMh65UOiJRO52tjCu7bDHQybZZEHMA526C1u14YNPu
  template:
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: plag
    type: Opaque
