apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sealed-secrets-backup
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sealed-secrets-backup
subjects:
  - kind: ServiceAccount
    name: sealed-secrets-backup
    namespace: sealed-secrets-backup
