apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: client-api-server-ingress
  namespace: client-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/router.middlewares: client-api-cors@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - stage.codedang.com
      secretName: client-api-server-tls
  rules:
    - host: stage.codedang.com
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: client-api-server
                port:
                  number: 4000
