apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring-minio

resources:
  - ../../base
  - ingress.yaml
  - tenant-config.yaml
  - users.yaml
  - minio-credentials.yaml
