apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-credentials
  namespace: redis
spec:
  # values are null on purpose, to be filled by kustomize patch
  encryptedData:
    password: null
  template:
    metadata:
      creationTimestamp: null
      name: redis-credentials
      namespace: redis
    type: Opaque
