---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-aws-cloudwatch
  namespace: monitoring-grafana
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCAOeZkRHESvDYSwRGHi91k2F4bGJ+2Sk40ytzcBMEPRtGSj23Y2H5V4L/rnJEuV93AHl5OXiid+LSyNn208ILgKX8PDgoETBUFBX+qArQxtA1lG8K9wic7eCvUOy3F8fZ5ALkIXbfxVt1iLoYPxjxfb4Hb2yILP24/06CFqzqI+rqu4o8rtkjp77dlp+DbGXa3DwvflXWEfjfp6VvP/IN6UIgoeXaqrSVaHPn30OnapqGMo+ZHL3571EspW4DYsPtpsh6sT3p7q4yPcFay9blCTQsCJLYR/31wFzgB3aOyjC73gtbkq6IVC7c8p9YrKZg7EYAcKokqgBU9+EWTG/ia7GbzPSfGyrnwWatUQtrxgaOaiuz/VU0X+012PDHd1WpXHH3r1sxqp8sZ6yQUtSiqN97qYwHqkMJeao7bO6zz3pF9oGHMFcY+t3U1LfJPfdhPxAzdwGhycmbHJqJ+7ZtcJhBQcg595IOxkSlW17mfXnwEVru/+2WU9ePx4PxhCeT7NL2xRk7+XLbbYEBlmUVS/4ze4rQhsBaoO2OiUIRzCI6jWffxeve45S4VwaCBeb1KWTNmS3AKX11dl9G99YvkxvhymvOQJHSIXTYUPwH1rKmhBo3VOUHNF3PShrYyga2Ro77tOcu7KYEo3Xx2c9SUAZyfm1waJyhwkqKaDXhNaLdjuxA2E5MfdZ/TPuBAxGRiC0qrI6+b2Z+HxvyWeiZZwFePPg==
    AWS_SECRET_ACCESS_KEY: AgCN8UDJUaC91ypp9bXu3h9Uwws7ZMjgQ11y0+Gt10hy9e5/wtmB12wKkW2V0ooyE6E93sIHHwzDHK+wSbsYdeNjaotV+DlF3VLToyP3AvG0FCSgrat4lA57ItqiaUnazn4SlrolR12PDzYawUPTf6trdwO3w+4wxdRodPQSvuHj1bhSJR74rM+boRAHUItp5IWxPvtbYGAGPyu7N9pmFvM8GNYaXJiyO7eDLczIi8xjnkwGv7vCAWRdu5BIqy9CZWvc4xEhGIkoXBZOZV/VluNdESt6ABYi7w8mplBMGt79YVzA4N9MRMCoc8uOr+q4pSpiqPYUgcZ6TiongoZS9u+ohManv7Ckbl/VBjO/CXVioT/GYpo0XJXcCnL1hERIfiCWpdRpE1G5k7fYa9K+bHI04ElLaOb+Y5DKmHaTaLhczpZRHqvM/tAswQ3aq+n3Jdl8GehvxB+U4TIKOdopdJnssIRyAlui7gdBUJtkbqwHYKGH3GN7A+inji9QIpwN6+gafjwLd6nrv03Jy9NLs4LZAdKpJSBpNSHhrGtNaZWZl55Ys3o0A+P5uEJClSxQIUmQJSPYKDfftBFmZA41BDdVrPTmeWYL6roz4uTRWKcCfXoqHNZ29w3IMdY++efFjDALj1twm/D+7l2Kq9GT/SXEgn67sjjt1P4sFY0Qt3Rm1Q+igjvVmIQg1tVcBpzZ1RmNEa/QjndPwEzyep2TDMfsDFYAXgSGOBuM3L5uPWsPtajsF+cRnHHf
  template:
    metadata:
      name: grafana-aws-cloudwatch
      namespace: monitoring-grafana
    type: Opaque
