---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-credentials
  namespace: rabbitmq
spec:
  encryptedData:
    password: AgB2AoqChZc6utMvKV6Iufgj93DIKIbn55f4hGoqSq5br9WssfOFxi+no1ehzoaBtt+dN/MY/Knt7jP6+qCExyusOihWlgkfOp0hDp+cQYqDekNqTi6R9RhFg8SxhOnzHx3dSJ2tqPkiWP0i7k+CmcsUh3gczaxB14rgiiKAKwLtESoSrQyKA6seEt1GBSYMqJVzKwPmujrPC1+mREsEqHDR7F/y9sGMQtCvcysFzAaKgtfKPMdq8nL3Qy9q9SIwFSm5UFVRkw5yvcLJISt/rZ3i+H7n1hzx/J6elIKVpSOXI1pAN+iFLjRnadO8DeAAbErG6pPNpVtaw6/nDvOPJWN+jravccPHPbtWCUkKD8eEKZyRrP16EI4u6AQ4KWCCvtmI9vxXInzuYcpPp718UBEXrgQ/rC6LfGGS1Vpfp36hu3O+/IM7f/JJ2BIBCPuZ92UOQGqMiQQ3hTJfNLCaHnlv4QOeLBHvEyeYyBf0Z9L1L8iVXJdym3xqX6U459sTlaJSkCc1U32vTSF6tljbmYdq7qG7/cD1Nx0zUiEbgkqXTDLkkeBG6Cd2G8ascE2KNa+FhXYIo0zqeQ6nt+I/i+7WklVqSZME3+cnsv6wwoRkHo4cvTO+QVSfV2u1+fogZKira2vkS3e7tU+74yOdXzAa7fajqWpB16VO9aiFNebdmpfawS4z2nvOsRIZzxNkc7IQGYf7fv4Z3g==
    username: AgDbKR7WW31q1mevJjotcYeAsRDvRiUFoqJUdWS5dLnaIqaMmSf/I98zL8wCm7j+gauAHa5UXGu/QhUvdhmecy+2mQiNiTEgb5e3hwHJ9F35yOhTLZmFghqA7EYbGGhlTMsmlH8hpo1iYwaggKDSqFffu6GRnL7BLL/SeIxk59IQQhN07YvD+Ego9T/6hKAw3khytcbuFI2JdPren0Q989V+vu7SpA2scttFtOa2gnJGyxSGcdh4p+S9szlyJby5vw+Eg03KceLKnu4suY0SsnyGTROjHmosGCAPtbS8MMGlSPuM4zEr4rQPzCTDos5rqgdWBMF6D1pFDzJpCd6NjVtr2/w8wbDzU8rUv50ucR2zYuv9EcU6YyXf+rvUG52LEWfyRQFl0rz8AJNkv9E+WoXytIvmyzd3H9te030dmx/+m7T82S3HAFWkppstpvWh7ZdxMYzPcWSFDGp2JiLXZF4SVYVFGlunMh3dOqZ1xXNLBWMIDOyo2s679EYJiWgKKCzjJGkYafQ1SpLsJ8ylFfhHxCuHqMXqu82EXILSCxU9OC4ngu4pBHdJbCiyekfOGEqd2gj+OTmofNyk/VRQ7clkIHl/fBNyb81rYbqMDB2JdnBV80LmhEB/Xho08TgGNQ6NIeTs5Y2xkV9NEcetqNNn1y7KARmasvgrzo3NFcm+b9kqhhbCdoJBUysU7eUihpxkev4k6Q==
  template:
    metadata:
      creationTimestamp: null
      name: admin-credentials
      namespace: rabbitmq
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
    type: Opaque
