apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test1-stage-onboarding
  namespace: argocd # ArgoCD 리소스가 저장되는 곳
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/environment: 'stage'
spec:
  project: default
  source:
    path: infra/k8s/onboarding/test1
    repoURL: https://github.com/skkuding/codedang
    targetRevision: onboarding # 주의: 작업 중인 브랜치명을 적어야 합니다 (main 아님)
    directory:
      recurse: true
  destination:
    namespace: onboarding # 실제 앱이 배포될 곳
    name: stage
  syncPolicy: # 자동 동기화 및 네임스페이스 생성 옵션
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
