apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iris

resources:
  - ../../base
  - aws-credentials.yaml
  - database-credentials.yaml

replicas:
  - name: iris
    count: 2

patches:
  - path: configmap.yaml
    target:
      kind: ConfigMap
      name: iris-env
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: iris
