---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: redis
spec:
  encryptedData:
    password: AgAwMc0d+lhEuyg+u5P2/KMrnD5AYlQ80smoq7MVTFVxUrCe1ciPQmp23UspJWeW5zYecy/wTnafSmvZxtU0wuTjUTzAc2w5UjMz1d/+SAgX6X5e8ahTJqn2FS9TVc+Fsl273768LOJXNZ1elnZlbp6ZAsIk06sMA+0+BTSJgaFwXnMvw1bYy1sqIZdDFUoyTdIRxymZLuJAraQpS7Y2XgQ49MRIqogxSqHAIc93nLMfOJa10WCs6Ygc/fgdBCblF/Ozk/z2l5A0YAX9DLOLV/C+aILpQNVvbqLNPKYISRkPl+x6Iv2kUMyJdSek4ZYNnK9hokxQ2FUNidgr5KlvFVwv3d9VGJMz1OxRkGLR2MRLbJyfAUAoXXnYzK9jOS9v+QI4ScHdJL/lj117dIY0mmUOIFNxzUailPCuZ19x0QdTQyRCDlHXL44uE1ewWxSu/XWp281df5yZgX8izwO5VRPG6t1COoa0ei7tXGNSGvqhNQZolgsZXX7C9cHLPIzRqqvzAJgxPmlckxkzXDkkcberWOZlnfgcUoLH7+4rtIS9mvjVEKDVP69OcB7Hd0jXg58Jqf9WOHjUZ7Ms414DOcbGHYKuMk6iesZU6Ho+zk6l3ssZF6ExhEeIIp1h2BTIe2pzgB92oTp5w/pHU+kqhDu9IC2nfJQxUJnBlmhSjkMw+oZcAtSkSX1UyTdfSsqJyJWnX3AlMIYZ5aNUbqKOjvpfSsx4rLjFFo2lnyKLxgTXXOxOqS8=
  template:
    metadata:
      name: redis-credentials
      namespace: redis
    type: Opaque
