apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-scale-set-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  source:
    repoURL: https://actions-runner-controller.github.io/actions-runner-controller
    chart: gha-runner-scale-set-controller
    targetRevision: 0.13.0
    helm:
      releaseName: gha-runner-scale-set-controller
  destination:
    namespace: arc-systems
    name: stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
