apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runner-scale-set
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: default
  sources:
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set
      targetRevision: 0.13.1
      helm:
        releaseName: arc-runner
        valueFiles:
          - $codedang/infra/k8s/arc/values.yaml
    - repoURL: https://github.com/skkuding/codedang
      targetRevision: main
      ref: codedang
  destination:
    namespace: arc-runners
    name: stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
