apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-stage
  namespace: argocd
  labels:
    app.kubernetes.io/environment: 'stage'
spec:
  project: default
  source:
    path: infra/k8s/minio
    repoURL: https://github.com/skkuding/codedang
    targetRevision: main
    directory:
      # kustomization.yaml is ignored if recurse is true
      recurse: false
  destination:
    namespace: minio
    name: stage
  syncPolicy:
    automated:
      # Prune disabled: requires manual review before removing resources
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
