apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: otel-operator
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  generators:
    - list:
        elements:
          - env: stage
          - env: production
  template:
    metadata:
      name: 'otel-operator-{{.env}}'
      annotations:
        argocd.argoproj.io/sync-wave: '-2'
      labels:
        app.kubernetes.io/environment: '{{.env}}'
    spec:
      project: default
      source:
        repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
        chart: opentelemetry-operator
        targetRevision: 0.106.0
        helm:
          releaseName: opentelemetry-operator
      destination:
        namespace: opentelemetry-operator-system
        name: '{{.env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
