apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: plag
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Required for argocd-image-updater to make changes to the Application
  # Otherwise, the changed image will be reverted to the original one by this ApplicationSet controller
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/source/kustomize/images
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  generators:
    - list:
        elements:
          - env: stage
            branch: main
          - env: production
            branch: release
  template:
    metadata:
      name: 'plag-{{.env}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      labels:
        app.kubernetes.io/environment: '{{.env}}'
      annotations:
        argocd-image-updater.argoproj.io/image-list: 'plag=ghcr.io/skkuding/codedang-plag:{{.env}}'
        argocd-image-updater.argoproj.io/plag.update-strategy: digest # Always pull the latest image of given tag
    spec:
      project: default
      source:
        path: 'infra/k8s/plag/overlays/{{.env}}'
        repoURL: https://github.com/skkuding/codedang
        targetRevision: '{{.branch}}'
        directory:
          # kustomization.yaml is ignored if recurse is true
          recurse: false
      destination:
        namespace: plag
        name: '{{.env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
