apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rabbitmq-cluster-operator
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  generators:
    - list:
        elements:
          - env: stage
          - env: production
  template:
    metadata:
      name: 'rabbitmq-cluster-operator-{{.env}}'
      annotations:
        argocd.argoproj.io/sync-wave: '-2'
      labels:
        app.kubernetes.io/environment: '{{.env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/rabbitmq/cluster-operator
        targetRevision: v2.19.1
        path: config/installation
      destination:
        namespace: rabbitmq-system
        name: '{{.env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rabbitmq-topology-operator
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  generators:
    - list:
        elements:
          - env: stage
          - env: production
  template:
    metadata:
      name: 'rabbitmq-topology-operator-{{.env}}'
      annotations:
        argocd.argoproj.io/sync-wave: '-2'
      labels:
        app.kubernetes.io/environment: '{{.env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/rabbitmq/messaging-topology-operator
        targetRevision: v1.18.3
        path: config/installation/cert-manager
      destination:
        namespace: rabbitmq-system
        name: '{{.env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
