name: CD - Failover ECS

on:
  push:
    branches: [release]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-2

jobs:
  build-and-push-ecr:
    name: Build & Push to ECR
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - service: client-api
            file: ./apps/backend/Dockerfile
            context: .
            target: client
            ecr_repo_name: codedang-client-api
            build_args: |
              target=client
              app_env=production

          - service: admin-api
            file: ./apps/backend/Dockerfile
            context: .
            target: admin
            ecr_repo_name: codedang-admin-api
            build_args: |
              target=admin
              app_env=production

          - service: iris
            file: apps/iris/Dockerfile
            context: apps/iris
            target: ''
            ecr_repo_name: codedang-iris
            build_args: |
              app_env=stage

          - service: plag
            file: apps/plag/Dockerfile
            context: apps/plag
            target: ''
            ecr_repo_name: codedang-plag
            build_args: |
              app_env=stage

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_FOR_ECR_PUSH }} # IAM: GitHubAction-ECRPush
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          push: true
          build-args: ${{ matrix.build_args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ matrix.ecr_repo_name }}:latest
            ${{ steps.login-ecr.outputs.registry }}/${{ matrix.ecr_repo_name }}:${{ github.sha }}

  deploy-amplify:
    name: Trigger Amplify Deployment
    runs-on: ubuntu-latest
    needs: build-and-push-ecr
    environment: production

    steps:
      - name: Trigger Amplify Webhook
        run: curl -X POST -d {} "${{ secrets.AMPLIFY_WEBHOOK }}" -H "Content-Type:application/json"
