# This workflow only builds and pushes Docker images.
# The rest of the deployment process is handled by ArgoCD.
name: CD - Production

on:
  push:
    branches: [release]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - target: client-api
            file: ./apps/backend/Dockerfile
            context: .
            build-args: |
              target=client
              app_env=production
          - target: admin-api
            file: ./apps/backend/Dockerfile
            context: .
            build-args: |
              target=admin
              app_env=production
          - target: iris
            file: ''
            context: apps/iris
            build-args: |
              app_env=stage
          - target: plag
            file: ''
            context: apps/plag
            build-args: |
              app_env=stage
          - target: runner-pod-manager
            file: ./apps/runner/pod-manager/Dockerfile
            context: .
            build-args: |
              app_env=production
          - target: runner-backend
            file: ./apps/runner/backend/Dockerfile
            context: .
            build-args: |
              app_env=production

    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.target.file }}
          context: '{{defaultContext}}:${{ matrix.target.context }}'
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          build-args: ${{ matrix.target.build-args }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/codedang-${{ matrix.target.target }}:production
            ghcr.io/${{ github.repository_owner }}/codedang-${{ matrix.target.target }}:${{github.sha}}

  build-frontend:
    name: Build and Push Image (Frontend)
    runs-on: arc-runner

    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          file: ./apps/frontend/Dockerfile
          context: '{{defaultContext}}:.'
          cache-from: |
            type=registry,ref=ghcr.io/skkuding/codedang-frontend:cache-stage
            type=registry,ref=ghcr.io/skkuding/codedang-frontend:cache-production
          cache-to: type=registry,ref=ghcr.io/skkuding/codedang-frontend:cache-production
          push: true
          build-args: ''
          tags: |
            ghcr.io/${{ github.repository_owner }}/codedang-frontend:production
            ghcr.io/${{ github.repository_owner }}/codedang-frontend:${{github.sha}}
